//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.RentalItems = new HashSet<RentalItem>();
        }
    
        public int Bookcode { get; set; }
        public string Title { get; set; }
        public Nullable<int> Author { get; set; }
        public Nullable<int> GenreID { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Available { get; set; }
        public Nullable<bool> BookStatus { get; set; }
        public Nullable<System.DateTime> Publish { get; set; }
        public byte[] IMG { get; set; }
    
        public virtual Author Author1 { get; set; }
        public virtual Genre Genre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentalItem> RentalItems { get; set; }
    }
}
